###----------------------------------------------------------------------------
###                             Variables
###----------------------------------------------------------------------------
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NjZkZmQyYTA0MGQ2MzY2NGYyZjU3ZCIsImlhdCI6MTcxOTAzMDg0OCwiZXhwIjoxNzE5MTE3MjQ4fQ.rZd2sdrt1fzo2eMpRR9xNBOXuAKApTDXQWtztdLen1o
###----------------------------------------------------------------------------
###       Pruebas para Administradores
###----------------------------------------------------------------------------

### Registrar Admin
POST http://localhost:3000/api/admin/register
Content-Type: application/json

{
  "username": "adminDany",
  "password": "securePassword"
  
}

### Iniciar Sesión como Admin
POST http://localhost:3000/api/admin/login
Content-Type: application/json

{
  "username": "adminDany",
  "password": "securePassword"
}

###----------------------------------------------------------------------------
###                     Pruebas para Comercios
###----------------------------------------------------------------------------

### Crear Comercio
POST http://localhost:3000/api/admin/comercios
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nombre": "Comercio Prueba Admin",
  "CIF": "CIF0007AD",
  "direccion": "Calle P",
  "email": "pruebaadminD@example.com",
  "telefono": "667788776"
}

### Consultar Todos los Comercios
GET http://localhost:3000/api/admin/comercios
Authorization: Bearer {{token}}

### Consultar Comercio por ID
GET http://localhost:3000/api/admin/comercios/6666e82d3a61f396bd4a1994
Authorization: Bearer {{token}}

### Actualizar Comercio
PUT http://localhost:3000/api/admin/comercios/6666edcde2cff37338880419
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nombre": "Super Comercio 1111111111",
  "direccion": "Calle Verdadera 456"
}

### Borrar Comercio 
DELETE http://localhost:3000/api/admin/comercios/6666edcde2cff37338880419
Authorization: Bearer {{token}}

###----------------------------------------------------------------------------
###               Pruebas para usuarios Registrados
###----------------------------------------------------------------------------

### Obtener todos los usuarios registrados
GET http://localhost:3000/api/admin/users
Authorization: Bearer {{token}}

### Obtener un usuarios registrados en especifico
GET http://localhost:3000/api/admin/user/6666eb5c3c108bd9108f92ed
Authorization: Bearer {{token}}

### Actualizar un usuario
PUT http://localhost:3000/api/admin/user/6666eb5c3c108bd9108f92ed
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nombre" : "nuevoNombre",
  "email" : "nuevoEmail@gmail.com",
  "ciudad" : "Madrid",
  
}

### Actualizar la contraseña de un usuario
PUT http://localhost:3000/api/admin/user/6666eb5c3c108bd9108f92ed/password
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "newPassword" : "P@ssw0rd"
}

### Actualizar el correo electronico de un usuario
PUT http://localhost:3000/api/admin/user/6666eb5c3c108bd9108f92ed/email
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "newEmail" : "nueviiiiiiiiiiiisimoEmail@gmail.com"
}

### Obtener un usuarios registrados en especifico
DELETE  http://localhost:3000/api/admin/user/6666eb5c3c108bd9108f92ed
Authorization: Bearer {{token}}