##Variables 
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NjA0MWUwYjliYzY4ZDA4NDM4NmJkNyIsImlhdCI6MTcxNzU4NDM1Mn0.YuRt1abVkCZN8Q8wQX4Zkzkxw_EUsHP19Z7_kQt4S-k

###Crear una nueva pagina de contenido 
POST http://localhost:3000/api/comercios
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "ciudad": "Madrid",
  "actividad": "Restaurante",
  "titulo": "Restaurante TOP",
  "resumen": "El mejor restaurante de la ciudad.",
  "text": ["Bienvenidos a nuestro restaurante.", "Ofrecemos una gran variedad de platos."],
  "fotos": []
  
}

###Borramos el contenido de un comercio
DELETE http://localhost:3000/api/comercios
Authorization: Bearer {{token}}

### Actualizar Contenido
PUT http://localhost:3000/api/comercios/contenido
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "ciudad": "Granada",
  "actividad": "Heladería",
  "titulo": "Helados Frescos",
  "resumen": "Los mejores helados artesanales.",
  "text": ["Helados de todos los sabores.", "Ingredientes naturales y frescos."],
  "fotos": ["foto1_comercio6.jpg"]

}

### Publicar un texto
POST http://localhost:3000/api/comercios/contenido/texts
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "text": "Este texto es increiblemente increible"
}

###Borrar texto
DELETE http://localhost:3000/api/comercios/contenido/texts/0
Authorization: Bearer {{token}}

### Subir una foto ---->FALTA
POST http://localhost:3000/api/comercios/contenido/fotos HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer {{token}}

--boundary
Content-Disposition: form-data; name="photo"; filename="shishaBar.jpg"
Content-Type: image/jpg

< ./shishaBar.jpg
--boundary--

###Borrar foto ---->FALTA
DELETE http://localhost:3000/api/comercios/contenido/fotos/0
Authorization: Bearer {{token}}

###Mostrar correo de usuarios de la misma ciudad y con el mismo interes
GET http://localhost:3000/api/comercios/contenido/intereses
Content-Type: application/json
Authorization: Bearer {{token}}

