##Variables 
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvbWVyY2lvM0BleGFtcGxlLmNvbSIsImlhdCI6MTcxNzQ1ODA0Mn0.6aHh9RE_kNdMVLKiFCmfgWHL4zMxaa_Fb5s9lGECUUM

###Crear una nueva pagina de contenido
POST http://localhost:3000/api/comercios/665a22a88870c0d87106f958
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvbWVyY2lvMkBleGFtcGxlLmNvbSIsImlhdCI6MTcxNzE4MzE0NH0.18bQUxVciMhN4OYVYYE2rWNjYPh8q04QLMwYgW-Amis

{
  "ciudad": "Madrid",
  "actividad": "Restaurante",
  "titulo": "Restaurante TOP",
  "resumen": "El mejor restaurante de la ciudad.",
  "text": ["Bienvenidos a nuestro restaurante.", "Ofrecemos una gran variedad de platos."],
  "fotos": [],
  "scoring": 0,
  "numScoring": 0,
  "reviews": []
}

###Borramos el contenido de un comercio
DELETE http://localhost:3000/api/comercios/665a22a88870c0d87106f958
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvbWVyY2lvMkBleGFtcGxlLmNvbSIsImlhdCI6MTcxNzE4MzE0NH0.18bQUxVciMhN4OYVYYE2rWNjYPh8q04QLMwYgW-Amis

### Actualizar Contenido
PUT http://localhost:3000/api/comercios/contenido/665e547ac5f6a9059d069659
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "ciudad": "Valencia",
  "actividad": "Tienda",
  "titulo": "Tienda TOP",
  "resumen": "La mejor tienda de la ciudad.",
  "text": ["Bienvenidos a nuestra tienda.", "Ofrecemos una gran variedad de productos."],
  "fotos": [],
  "scoring": 0,
  "numScoring": 0,
  "reviews": []

}

### Publicar un texto
POST http://localhost:3000/api/comercios/contenido/665786cdc663c63590307de7/texts
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "text": "Este es el segundo texto añadido"
}

###Borrar texto
DELETE http://localhost:3000/api/comercios/contenido/665786cdc663c63590307de7/texts/0
Authorization: Bearer {{token}}

### Subir una foto
POST http://localhost:3000/api/comercios/contenido/665786cdc663c63590307de7/fotos HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer {{token}}

--boundary
Content-Disposition: form-data; name="photo"; filename="shishaBar.jpg"
Content-Type: image/jpg

< ./shishaBar.jpg
--boundary--

###Borrar foto
DELETE http://localhost:3000/api/comercios/contenido/665786cdc663c63590307de7/fotos/0
Authorization: Bearer {{token}}

###Mostrar correo de usuarios de la misma ciudad y con el mismo interes
GET http://localhost:3000/api/comercios/contenido/intereses/665e5452c5f6a9059d06964f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvbWVyY2lvMUBleGFtcGxlLmNvbSIsImlhdCI6MTcxNzQ1ODAwMn0.WClPyeV5dV6zTs85l5jl3HIEYlqfZdY5Z5EJbYIJTnk

