### OBTENER LISTA DE COMERCIOS

GET http://localhost:3000/api/comercios

### OBTENER UN COMERCIO POR EL CIF

GET http://localhost:3000/api/comercios/B87654321C

### CREAR UN NUEVO COMERCIO

POST http://localhost:3000/api/comercios
Content-Type: application/json

{
  "nombre": "Moda Urbana",
  "CIF": "F987654322X",
  "direccion": "Paseo del Prado, 45, Barcelona",
  "email": "modaurbana@tienda.com",
  "telefono": "936666890",
  "id_pagina": 5
}

### MODIFICAR UN COMERCIO A PARTIR DE SU CIF

PUT http://localhost:3000/api/comercios/C987654321D
Content-Type: application/json

{
    "nombre": "Navantia",
    "CIF": "111111111Y",
    "direccion": "Av Los Nuevos Mares, 1, Cadiz",
    "email": "navantiae@test.com",
    "telefono": "111111111",
    "id_pagina": 4
}

### BORRAR UN COMERCIO A PARTIR DE SU CIF (PERMITE ELEGIR ENTRE BORRADO LOGICO Y FISICO)
DELETE  http://localhost:3000/api/comercios/111111111Y?deleteMode=hard

###CREAR UN COMERCIO
POST http://localhost:3000/api/admin
Content-Type: application/json

{
    "nombre": "Prueba2",
    "CIF": "131313131B",
    "direccion": "Av Los Nuevos Mares, 1, Cadiz",
    "email": "Prueba2@test.com",
    "telefono": "112232142",
    "id_pagina": 12
}

###ACTUALIZAR UN COMERCIO
PUT http://localhost:3000/api/admin/662d440fbe6c90d8670ac283
Content-Type: application/json

{
    "nombre": "Prueba2",
    "CIF": "131313131B",
    "direccion": "Viva españa , viva el rey , viva la orden y la ley",
    "email": "Prueba2@test.com",
    "telefono": "112232142",
    "id_pagina": 12
}

###Get comercio by id

GET http://localhost:3000/api/admin/662d440fbe6c90d8670ac283

###DELETE COMERCIO
DELETE  http://localhost:3000/api/admin/662d440fbe6c90d8670ac283