###----------------------------------------------------------------------------
###                             Variables
###----------------------------------------------------------------------------
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ODEzYzlmMWNjZDNhZDk2OTdjMTU2NiIsImlhdCI6MTcxOTc2MzkwOCwiZXhwIjoxNzE5ODUwMzA4fQ.mgsMtKLaOtyJc5H5pIFY-rGKa4PJxdMzeOrl2XfH9Dw
###----------------------------------------------------------------------------
###       Pruebas para Administradores
###----------------------------------------------------------------------------

### Registrar Admin
POST http://localhost:3000/api/admin/register
Content-Type: application/json

{
  "username": "admin1",
  "password": "admin1"
  
}

### Iniciar Sesión como Admin
POST http://localhost:3000/api/admin/login
Content-Type: application/json

{
  "username": "admin1",
  "password": "admin1"
}

###----------------------------------------------------------------------------
###                     Pruebas para Comercios
###----------------------------------------------------------------------------

### Crear Comercio
POST http://localhost:3000/api/admin/comercios
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nombre": "Comercio Prueba Admin",
  "CIF": "CIF0007AD",
  "direccion": "Calle P",
  "email": "pruebaadminD@example.com",
  "telefono": "667788776"
}

### Consultar Todos los Comercios
GET http://localhost:3000/api/admin/comercios
Authorization: Bearer {{token}}

### Consultar Comercio por ID
GET http://localhost:3000/api/admin/comercios/66813e0442450cbfd1a43f57
Authorization: Bearer {{token}}

### Actualizar Comercio
PUT http://localhost:3000/api/admin/comercios/66813e0442450cbfd1a43f57
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nombre": "Super Comercio 1111111111",
  "direccion": "Calle Verdadera 456"
}

### Borrar Comercio 
DELETE http://localhost:3000/api/admin/comercios/66813e0442450cbfd1a43f57
Authorization: Bearer {{token}}

###----------------------------------------------------------------------------
###               Pruebas para usuarios Registrados
###----------------------------------------------------------------------------

### Obtener todos los usuarios registrados
GET http://localhost:3000/api/admin/users
Authorization: Bearer {{token}}

### Obtener un usuarios registrados en especifico
GET http://localhost:3000/api/admin/user/665fbef2560e494814e15cf8
Authorization: Bearer {{token}}

### Actualizar un usuario
PUT http://localhost:3000/api/admin/user/665fbef2560e494814e15cf8
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nombre" : "nuevoNombre",
  "email" : "nuevoEmail@gmail.com",
  "ciudad" : "Madrid"
  
}

### Actualizar la contraseña de un usuario
PUT http://localhost:3000/api/admin/user/665fbef2560e494814e15cf8/password
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "newPassword" : "P@ssw0rd"
}

### Actualizar el correo electronico de un usuario
PUT http://localhost:3000/api/admin/user/665fbef2560e494814e15cf8/email
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "newEmail" : "nueviiiiiiiiiiiisimoEmail@gmail.com"
}

### Obtener un usuarios registrados en especifico
DELETE  http://localhost:3000/api/admin/user/665fbef2560e494814e15cf8
Authorization: Bearer {{token}}